# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('fragment_type', models.TextField(choices=[(b'plaintext', b'Plaintext'), (b'html', b'HTML'), (b'markdown', b'Markdown'), (b'image', b'Image'), (b'code', b'Code'), (b'embed', b'Embed')], default=b'plaintext')),
                ('is_sanitized', models.BooleanField(default=False)),
                ('credit', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('language', models.TextField(blank=True, choices=[(b'generic', b'Generic'), (b'python', b'Python'), (b'bash', b'Bash'), (b'javascript', b'JavaScript'), (b'html', b'HTML'), (b'css', b'CSS')])),
                ('embed_type', models.TextField(blank=True, choices=[(b'raw', b'Raw'), (b'vimeo', b'Vimeo'), (b'youtube', b'Youtube'), (b'tweet', b'Tweet'), (b'instagram', b'Instagram')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.TextField()),
                ('tldr', models.TextField(blank=True)),
                ('state', models.TextField(choices=[(b'draft', b'Draft'), (b'published', b'Published'), (b'archived', b'Archived')], default=b'draft')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.Organization')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.AddField(
            model_name='fragment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='fragments.Post'),
        ),
    ]
